{% set name = "pyxem" %}
{% set version = "0.15.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3d451180d64ae22f6b9933c9598635693857d1241e6ca3558b9671802e945350


build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python >=3
  run:
    - python >=3
    - scikit-image >=0.19.0
    - matplotlib-base >=3.3
    - scikit-learn >=1.0
    - hyperspy-base >=1.7.0
    - diffsims >=0.5
    - lmfit >=0.9.12
    - ipywidgets
    - pyfai-base
    - numba
    - orix >=0.9

test:
  requires:
    - pytest>=5.0
    - pytest-cov>=2.8.1
    - coveralls>=1.10
    - coverage>=5.0
  imports:
    - pyxem
    - pyxem.utils
    - pyxem.detectors
    - pyxem.components
    - pyxem.generators
    - pyxem.signals
    - pyxem.libraries
    - pyxem.dummy_data
  commands:
    - pytest --pyargs pyxem -k "not test_segments and not test_virtual_dark_field_image"

about:
  home: https://github.com/pyxem/pyxem
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: An open-source Python library for crystallographic diffraction microscopy
  doc_url: http://pyxem.github.io/pyxem-website/

extra:
  recipe-maintainers:
    - CSSFrancis
    - dnjohnstone
    - pc494
    - magnunor
